#!/bin/bash

declare -a formparams
for image in "$@"; do
  formparams+=(-F "files[]=@$image")
done

response=$(curl -s http://pomf.se/upload.php "${formparams[@]}")
if [[ $(jq -c -r '.success' <<< "$response") == true ]]; then
  jq -c -r '"http://a.pomf.se/\(.files[]|.url + "  " + .name)"'
else
  jq -c -r '"Failed: \"\(.error)\""'
  exit 1
fi <<< "$response"
